### ISSUE TITLE
foreach

### ISSUE THREAD

**Issue by tommiehansen** [desandro/classie#12]
This lib lacks adding/removing etc to multiple elements which is the only case where one would need a helper since element.classList.remove() etc doesn't need helpers.

I suggest adding the term 'multi' or something similar:

classie.addMulti(collection, 'class');
classie.removeMulti(collection, 'class');
classie.toggleMulti(collection, 'class');

Else one has to litter ones code with stuff like:

    var element = document.querySelectorAll('div'),
    i=0,
    l = element.length;

    for(i; i < l; i++){
        classie.toggle(element[i], 'myClass');
    }

**Comment by desandro** [comment]
Hi! Thanks for the suggestion. I feel this is out of scope for classie. I'd rather you use your own forEach handler, or loops, or whatever you like. Let's keep classie small :)

**Comment by kevinjamesus86** [comment]
@tommiehansen you could do something like this. I avoided extending classie itself by returning a new object with the classie methods each-ified.

```js
var classier = (function(classier) {

  for (var method in classie) {
    classier[method] = wrapForEach(method);
  }

  return classier;

  /////
  /////

  function wrapForEach(method) {
    var fn = classie[method];
    return function(elem, c) {
      var classes = c.match(/\S+/g),
        length = classes.length;
      while (length--) {
        fn(elem, classes[length]);
      }
    };
  }

})({});
```

which leaves you with

```js
// note: the long hand methods are each-ified too
classier.has(el, 'class-one class-two');
classier.add(el, 'class-one class-two');
classier.remove(el, 'class-one class-two');
classier.toggle(el, 'class-one class-two');
```
