### ISSUE TITLE
Classie not working when using .querySelectorAll or .getElementsByClassName()

### ISSUE THREAD

**Issue by ryanbrownhill** [desandro/classie#17]
Discovered an problem when using classie when getting elements using `querySelectorAll` or `.getElementsByClassName()` methods

**Comment by desandro** [comment]
Classie works with single elements. https://github.com/desandro/classie/issues/12#issuecomment-86116959

> I'd rather you use your own forEach handler, or loops, or whatever you like. Let's keep classie small :)

**Comment by ryanbrownhill** [comment]
:ok_hand:
