### ISSUE TITLE
usage w/ angular js 

### ISSUE THREAD

**Issue by james075** [desandro/classie#18]
Hi, it may sound dummy but I got some errors using classie with MEANJS boilerplate implementation that I can't fix.

1- I added the lib in the config file:

![screen shot 2015-05-21 at 5 28 24 pm](https://cloud.githubusercontent.com/assets/5047120/7752283/deeb16b4-ffde-11e4-98a9-d411b1c85b1d.png)

2- implementation:

```
            if (!classie.has(wrapper, 'toggled')) {
                classie.toggle(wrapper, 'toggled');
            }
            // on click event
            $('#menu-toggle').on('click', function (event) {
                event.preventDefault();
                classie.toggle(wrapper, 'toggled');
            });
```

Everything works, but I got these warning:

![screen shot 2015-05-21 at 5 30 06 pm](https://cloud.githubusercontent.com/assets/5047120/7752329/17d13b3e-ffdf-11e4-8820-0fe032be1cf4.png)

How could I integrate Classie with Angular ?

**Comment by desandro** [comment]
This is outside my area of expertise, so I'm sorry I won't be able to help here.

**Comment by MauricioJr** [comment]
@desandro I faced the same problem trying to use with RequireJS.

**Comment by adriancaragea** [comment]
@desandro I have the same issue with classie is not defined when I am using dojo which has AMD. I see that you define classie by doing define( classie ), but how can I retrieve the object and use it further in my code?
