### ISSUE TITLE
AMD usage for classie, "classie is not defined"

### ISSUE THREAD

**Issue by adriancaragea** [desandro/classie#21]
@desandro I have an issue with "classie is not defined" when I am using dojo which has AMD. I see that you define classie by doing define( classie ), but how can I retrieve the object and use it further in my code?

I have also posted a question regarding this on stack-overflow if you want more details:
http://stackoverflow.com/questions/33002527/classie-undefined-how-to-bring-anonymous-objects-in-scope-with-dojo-amd

**Comment by desandro** [comment]
Here's [DOJO module loading documentation](https://dojotoolkit.org/documentation/tutorials/1.10/modules/). You should be able to load `classie like

``` js
require([
  'path/to/classie'
], function( classie ) {
  classie.add( elem, "class-name" )
})
```

**Comment by adriancaragea** [comment]
Thank you @desandro  for taking the time to answer my question, but I am including the class in the file where I am using "classie.add( elem, "class-name" )" so classie is not in a different file than where I am using. I am doing this because I am using it as a inserted js code on other web apps for tracking. Do you know what I am supposed to put into 'path/to/classie' when the classie code and the code that is using classie are in the same page, in the same file? I have did not find this in any of the documentation provided by dojo or other libraries that are using AMD.

**Comment by desandro** [comment]
Have you tried using `window.classie` ?

**Comment by adriancaragea** [comment]
Say I have, it is still not working, did it work for you?

**Comment by desandro** [comment]
Sorry but I won't be able to debug this issue.

**Comment by adriancaragea** [comment]
I have declared define with null in my scope so that it will not use AMD even if it is available. If it supports AMD, it would be a good idea to also provide example on how to use it even if it means using it in a different file and load it with require because the class definition behaves different when AMD is available.
