### ISSUE TITLE
refer to polyfill instead

### ISSUE THREAD

**Issue by jimmywarting** [desandro/classie#24]
if this is not longer supported then i suggest you refer to a polyfill instead

I used a plugin that was dependent of yours classie lib, if he would have used this [classList polyfill](https://github.com/eligrey/classList.js/) instead then i could choose if i wanted to include the polyfill or not. I could decide if i only wanted to support the evergreen browser - but instead i also had to include this classie lib 👎

**Comment by desandro** [comment]
Thanks but no thanks. Polyfills have a different use case. Classie is not under further development, but it still does its purpose just fine — being a class helper.
