### ISSUE TITLE
how to add a wordpress post permalink with classie.add function?

### ISSUE THREAD

**Issue by IlirBajrami** [desandro/classie#25]
hi there,
im trying to create a wordpress theme from a html template. to load an article it uses classie.js and it uses classie.add which adds the class to show that particular article, however i want it to show my wordpress post via its permalink. is it possible and how?

thanks!

**Comment by desandro** [comment]
Hello! `classie` is deprecated and no longer supported. Sorry, I won't be able to provide a solution here.
