### ISSUE TITLE
WIN10 IE 14 Edge and 15 Edge - Page reloads when pressing a Key

### ISSUE THREAD

**Issue by meincms** [desandro/classie#26]
Somehow the Script seems to fail on Internet Explorer 14 Edge and 15 Edge on Windows 10.
As soon as s.b. clicks into a field and directly starts to type a letter, the page reloads. 

I could 't figure out where this issue comes from, but my forms won't work anymore on the mentioned browser.

**Comment by desandro** [comment]
**classie is deprecated**

> Use classie only if you need to support older browsers that do not support classList. classList is supported in IE10+, Android 3+, iOS Safari 5.1+, and modern evergreen browsers. [Can I use classList](https://caniuse.com/#search=classlist)?
